# =============================================================================
# 08h_25km_Multipanel_Synthesis.R
#
# Generates a premium, publication-quality multipanel figure for the 25km scale:
#   - Panel A: Scatterplot of empirical data, fitted Bayesian Sigmoid model
#              (GEDI UOI modeled as a non-linear function of Mammal Biomass index),
#              and robust 95% posterior Credible Interval ribbon.
#   - Panel B: Boxplots of GEDI UOI pixels inside each buffered MCP polygon with
#              individual pixel jitter overlaid, ordered by cluster biomass index
#              and colored by continent.
#   - Panel C: Spatial maps for each continent:
#              - GEDI UOI (25km) with highly informative viridis palette (0.91 - 0.97)
#              - Predicted Biomass Index (25km) generated by inverting the fitted
#                Bayesian Sigmoid model, with winsorized inferno palette (0 - 2000)
#
# Saves figure to:
#   - outputs/congo_ct_gee_25km_multipanel_synthesis.png
# Copies to brain artifacts folder:
#   - /home/j/.gemini/antigravity/brain/913e5cea-7c99-4b21-8124-ea8455da8457/
# =============================================================================

library(terra)
library(ggplot2)
library(tidyterra)
library(cowplot)
library(dplyr)
library(readr)
library(brms)
library(scales)

cat("=== Starting 25km Multipanel Synthesis Figure Generation ===\n\n")

# --- 1. Load Theme, Colors, and GIS Polygons ---------------------------------
source("code/functions/theme_pnas.R")

# Ensure outputs directory exists
dir.create("outputs", recursive = TRUE, showWarnings = FALSE)

# Load robust cluster buffered MCPs
geojson_path <- "outputs/camera_traps_robust_buffered_mcps.geojson"
if (!file.exists(geojson_path)) {
  stop("Camera trap buffered MCPs GeoJSON missing: ", geojson_path, 
       "\nPlease run python3 code/visualise_camera_traps.py first to generate it.")
}
mcps <- terra::vect(geojson_path)
mcps_congo <- mcps[as.vector(values(mcps)$region) == "Congo", ]
mcps_amazon <- mcps[as.vector(values(mcps)$region) == "Amazon", ]
cat(sprintf("✓ Loaded %d Congo and %d Amazon study polygons.\n", nrow(mcps_congo), nrow(mcps_amazon)))

# Establish consistent cropped geographic study extents with 1.0 degree padding
study_extent_congo <- ext(mcps_congo)
study_extent_congo <- ext(
  xmin(study_extent_congo) - 1.0,
  xmax(study_extent_congo) + 1.0,
  ymin(study_extent_congo) - 1.0,
  ymax(study_extent_congo) + 1.0
)

study_extent_amazon <- ext(mcps_amazon)
study_extent_amazon <- ext(
  xmin(study_extent_amazon) - 1.0,
  xmax(study_extent_amazon) + 1.0,
  ymin(study_extent_amazon) - 1.0,
  ymax(study_extent_amazon) + 1.0
)

base_family <- if (requireNamespace("showtext", quietly = TRUE)) "Roboto Condensed" else "sans"

# --- 2. Load 25 km Spatial Stacks --------------------------------------------
r_congo_path <- "outputs/EOdata/analysis_stack_25000_Congo.tif"
r_amazon_path <- "outputs/EOdata/analysis_stack_25000_Amazon.tif"

if (!file.exists(r_congo_path) || !file.exists(r_amazon_path)) {
  stop("25km GEE geotiffs missing. Please run GEE aggregation first.")
}

r_congo <- rast(r_congo_path)
r_amazon <- rast(r_amazon_path)

aggregate_names <- c("frip", "frip_mk_tau", "uoi", "uoi_sd", "rh98", "gedi_n",
                     "elevation", "slope", "hnd", "precip", "clay", "forest_fraction")
names(r_congo) <- aggregate_names
names(r_amazon) <- aggregate_names

# --- 3. Extract Pixel Values and Merge Metadata -----------------------------
cat("  Extracting pixel values inside MCP polygons...\n")
extracted_congo <- terra::extract(r_congo, mcps_congo, df = TRUE, touches = TRUE)
mcp_congo_df <- as.data.frame(mcps_congo)
mcp_congo_df$ID <- 1:nrow(mcp_congo_df)
pixel_congo <- merge(extracted_congo, mcp_congo_df, by = "ID") %>%
  filter(!is.na(uoi)) %>%
  select(-ID) %>%
  mutate(basin = "Congo")

extracted_amazon <- terra::extract(r_amazon, mcps_amazon, df = TRUE, touches = TRUE)
mcp_amazon_df <- as.data.frame(mcps_amazon)
mcp_amazon_df$ID <- 1:nrow(mcp_amazon_df)
pixel_amazon <- merge(extracted_amazon, mcp_amazon_df, by = "ID") %>%
  filter(!is.na(uoi)) %>%
  select(-ID) %>%
  mutate(basin = "Amazon")

pixel_data <- rbind(pixel_congo, pixel_amazon)

# Aggregate to Polygon Means for modeling
joined_data <- pixel_data %>%
  group_by(cluster_id, region, basin, trap_days, n_species, B_H_index, M_H_index, B_H_gt50, B_H_gt100, megafauna_fraction) %>%
  summarise(
    n_pixels = n(),
    uoi_sd = ifelse(is.na(sd(uoi, na.rm = TRUE)), 0, sd(uoi, na.rm = TRUE)),
    uoi = mean(uoi, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  filter(trap_days >= 10)

# Compute standard error of the mean
joined_data <- joined_data %>%
  mutate(uoi_se = uoi_sd / sqrt(n_pixels))

# Regularizing constant
reg_uoi <- median(joined_data$uoi_se[joined_data$uoi_se > 0], na.rm = TRUE)
if (is.na(reg_uoi) || reg_uoi == 0) reg_uoi <- 1e-4

# Dual-weight precision framework
joined_data <- joined_data %>%
  mutate(w_uoi = log10(trap_days) / (uoi_se + reg_uoi))

# Weight normalization (mean = 1)
joined_data$w_uoi_norm <- joined_data$w_uoi / mean(joined_data$w_uoi)

# --- 4. Fit Weight-Normalized Bayesian Sigmoid Model (25 km) ------------------
cat("  Formulating and fitting Bayesian non-linear Sigmoid model (UOI predicted by Biomass)...\n")

# Scale biomass to range [0, 4.5] for better optimization stability
joined_data$B_scaled <- joined_data$B_H_index / 1000

# Formula for non-linear sigmoid:
# UOI = uoimin + (uoimax - uoimin) / (1 + exp(-k * (B_scaled - x0)))
b_formula <- bf(
  uoi | weights(w_uoi_norm) ~ uoimin + (uoimax - uoimin) / (1 + exp(-k * (B_scaled - x0))),
  uoimin + uoimax + k + x0 ~ 1,
  nl = TRUE
)

# Priors with physical bounds to constrain parameters to ecologically realistic ranges:
#   - uoimin: baseline openness around 0.915
#   - uoimax: maximum plateau around 0.965
#   - k: positive steepness prior, scaled to B_scaled (which spans ~4 units)
#   - x0: midpoint of steep change in scaled biomass (e.g., around 1.1, i.e., 1100 kg/ha)
b_priors <- c(
  prior(normal(0.915, 0.02), nlpar = "uoimin", lb = 0.85, ub = 0.95),
  prior(normal(0.965, 0.02), nlpar = "uoimax", lb = 0.94, ub = 0.99),
  prior(normal(2.5, 1.5), nlpar = "k", lb = 0.1, ub = 10.0),
  prior(normal(1.2, 0.5), nlpar = "x0", lb = 0.1, ub = 4.0)
)

# Fit the non-linear model using brms/Stan
fit_bayesian <- brm(
  formula = b_formula,
  data = joined_data,
  family = gaussian(),
  prior = b_priors,
  chains = 4,
  cores = 4,
  iter = 4000,
  warmup = 2000,
  control = list(adapt_delta = 0.98),
  backend = "rstan",
  seed = 42
)

cat("\nBayesian model fit summary:\n")
print(summary(fit_bayesian))
cat("\n")

# Extract posterior parameter estimates for mapping
fe <- fixef(fit_bayesian)
uoimin_val <- fe["uoimin_Intercept", "Estimate"]
uoimax_val <- fe["uoimax_Intercept", "Estimate"]
k_val      <- fe["k_Intercept", "Estimate"]
x0_val     <- fe["x0_Intercept", "Estimate"]

cat(sprintf("✓ Bayesian parameters extracted:\n"))
cat(sprintf("  uoimin = %.4f, uoimax = %.4f, k = %.4f, x0 = %.4f\n", 
            uoimin_val, uoimax_val, k_val, x0_val))

# --- 5. PANEL A: Scatter Plot and Model Fit ----------------------------------
cat("  Generating Panel A (Scatterplot with Bayesian Sigmoid fit)...\n")

# Create sequence of Biomass values for plotting the fit
# Spans 0 to 7500 (representing scaled 0 to 7.5) to capture full range and extrapolation
biomass_seq <- seq(0, 7500, length.out = 300)
pred_df <- data.frame(
  B_H_index = biomass_seq,
  B_scaled = biomass_seq / 1000
)

# Predict expected value of UOI and its 95% Credible Interval
fitted_draws <- fitted(fit_bayesian, newdata = pred_df)
pred_df$fit <- fitted_draws[, "Estimate"]
pred_df$lower <- fitted_draws[, "Q2.5"]
pred_df$upper <- fitted_draws[, "Q97.5"]

stat_label <- sprintf(
  "Bayesian Sigmoid (25 km)\nN = %d clusters\nConverged (Rhat = 1.00)",
  nrow(joined_data)
)

p_scatter <- ggplot() +
  # 95% Credible Interval ribbon (forest green)
  geom_ribbon(
    data = pred_df,
    aes(x = B_H_index, ymin = lower, ymax = upper),
    fill = "#2E7D32",
    alpha = 0.15
  ) +
  # Regression curve
  geom_line(
    data = pred_df,
    aes(x = B_H_index, y = fit),
    color = "#1B5E20",
    linewidth = 0.8
  ) +
  # Empirical points (colored by UOI Spatial SE, shaped by continent)
  geom_point(
    data = joined_data,
    aes(x = B_H_index, y = uoi, size = trap_days,
        fill = uoi_se, shape = basin),
    color = "black",
    stroke = 0.4,
    alpha = 0.85
  ) +
  scale_shape_manual(
    values = c("Congo" = 21, "Amazon" = 24),
    name = "Continent"
  ) +
  scale_size_continuous(
    range = c(1.5, 6.0),
    name = "Effort (Days)"
  ) +
  scale_fill_viridis_c(
    option = "magma",
    name = "UOI Spatial SE",
    guide = guide_colorbar(
      title.position = "top",
      barwidth = unit(1.8, "cm"),
      barheight = unit(0.12, "cm")
    )
  ) +
  annotate(
    "text",
    x = 100, y = 0.969,
    label = stat_label,
    hjust = 0, vjust = 1,
    family = base_family,
    size = 2.4,
    fontface = "bold",
    color = "grey20"
  ) +
  scale_x_continuous(limits = c(0, 7500), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0.91, 0.98), expand = expansion(mult = c(0, 0.01))) +
  theme_pnas(base_size = 7.5) +
  theme(
    legend.position = "bottom",
    legend.box = "horizontal",
    legend.title = element_text(size = 6.0, face = "bold"),
    legend.text = element_text(size = 5.5),
    legend.key.size = unit(0.28, "cm"),
    legend.margin = margin(t = -5, r = 0, b = 0, l = 0, unit = "pt")
  ) +
  labs(
    title = "A. Bayesian Sigmoid Model Fit & Extrapolation",
    x = "Total Mammal Biomass Index",
    y = "GEDI Understory Openness Index (UOI)"
  )

# --- 6. PANEL B: Boxplots with Jittered Pixels -------------------------------
cat("  Generating Panel B (Boxplots with jittered pixels)...\n")

pixel_data_filtered <- pixel_data %>%
  filter(trap_days >= 10)

# Sort cluster_id by actual standing biomass index (B_H_index)
pixel_data_filtered$cluster_id <- reorder(pixel_data_filtered$cluster_id, pixel_data_filtered$B_H_index)

p_box <- ggplot(pixel_data_filtered, aes(x = cluster_id, y = uoi)) +
  # Semi-transparent boxplots colored by continent
  geom_boxplot(
    aes(fill = basin, color = basin),
    alpha = 0.22,
    linewidth = 0.3,
    outlier.shape = NA
  ) +
  # Jittered individual pixel points
  geom_jitter(
    aes(color = basin),
    width = 0.15,
    height = 0,
    size = 0.7,
    alpha = 0.65
  ) +
  scale_fill_manual(
    values = pal_basin,
    name = "Continent"
  ) +
  scale_color_manual(
    values = pal_basin,
    name = "Continent"
  ) +
  theme_pnas(base_size = 7.5) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 5.0, family = base_family),
    legend.position = "bottom",
    legend.title = element_text(size = 6.0, face = "bold"),
    legend.text = element_text(size = 5.5),
    legend.margin = margin(t = -5, r = 0, b = 0, l = 0, unit = "pt")
  ) +
  labs(
    title = "B. Within-Cluster Pixel Heterogeneity (25 km)",
    x = "Camera Trap Cluster (Ordered by Mammal Biomass Index)",
    y = "Pixel Understory Openness (UOI)"
  )

# --- 7. PANEL C: Spatial Maps of UOI & Predicted Biomass ----------------------
cat("  Generating Panel C Spatial Maps (25 km)...\n")

# --- 7.1 Congo Predictions and Mapping
cat("    Processing Congo spatial predictions using inverted Bayesian Sigmoid...\n")
r_congo_cropped <- crop(r_congo, study_extent_congo)
congo_cells <- as.data.frame(r_congo_cropped[["uoi"]], cells = TRUE, xy = TRUE, na.rm = TRUE)
names(congo_cells)[names(congo_cells) == "uoi"] <- "uoi"

# Clamp observed GEDI UOI slightly within fitted limits (uoimin_val, uoimax_val) to avoid domain errors
eps <- 1e-4
congo_cells$uoi_clamped <- pmax(uoimin_val + eps, pmin(uoimax_val - eps, congo_cells$uoi))
congo_cells$pred <- 1000 * (x0_val - (1 / k_val) * log((uoimax_val - congo_cells$uoi_clamped) / (congo_cells$uoi_clamped - uoimin_val)))
congo_cells$pred <- pmax(0, congo_cells$pred)

r_pred_congo <- rast(r_congo_cropped[["uoi"]])
names(r_pred_congo) <- "pred"
values(r_pred_congo) <- NA
r_pred_congo[congo_cells$cell] <- as.vector(congo_cells$pred)

# --- 7.2 Amazon Predictions and Mapping
cat("    Processing Amazon spatial predictions using inverted Bayesian Sigmoid...\n")
r_amazon_cropped <- crop(r_amazon, study_extent_amazon)
amazon_cells <- as.data.frame(r_amazon_cropped[["uoi"]], cells = TRUE, xy = TRUE, na.rm = TRUE)
names(amazon_cells)[names(amazon_cells) == "uoi"] <- "uoi"

# Clamp observed GEDI UOI slightly within fitted limits (uoimin_val, uoimax_val) to avoid domain errors
amazon_cells$uoi_clamped <- pmax(uoimin_val + eps, pmin(uoimax_val - eps, amazon_cells$uoi))
amazon_cells$pred <- 1000 * (x0_val - (1 / k_val) * log((uoimax_val - amazon_cells$uoi_clamped) / (amazon_cells$uoi_clamped - uoimin_val)))
amazon_cells$pred <- pmax(0, amazon_cells$pred)

r_pred_amazon <- rast(r_amazon_cropped[["uoi"]])
names(r_pred_amazon) <- "pred"
values(r_pred_amazon) <- NA
r_pred_amazon[amazon_cells$cell] <- as.vector(amazon_cells$pred)

# --- 7.3 Map Panel Helper
make_map_panel <- function(r_data, mcps_vector, palette_option, title, legend_title, limits = NULL, winsorize = FALSE) {
  p <- ggplot() +
    geom_spatraster(data = r_data)
  
  if (winsorize) {
    p <- p + scale_fill_viridis_c(
      option = palette_option,
      name = legend_title,
      limits = limits,
      oob = scales::squish,
      na.value = "transparent",
      guide = guide_colorbar(
        title.position = "top",
        barwidth = unit(1.2, "cm"),
        barheight = unit(0.08, "cm")
      )
    )
  } else {
    p <- p + scale_fill_viridis_c(
      option = palette_option,
      name = legend_title,
      limits = limits,
      na.value = "transparent",
      guide = guide_colorbar(
        title.position = "top",
        barwidth = unit(1.2, "cm"),
        barheight = unit(0.08, "cm")
      )
    )
  }
  
  p <- p +
    geom_spatvector(data = mcps_vector, fill = NA, color = "black", linewidth = 0.25, alpha = 0.8) +
    theme_pnas(base_size = 5.5) +
    theme(
      legend.position = "right",
      legend.title = element_text(size = 4.5, face = "bold"),
      legend.text = element_text(size = 4.0),
      legend.key.height = unit(0.18, "cm"),
      legend.key.width = unit(0.08, "cm"),
      legend.margin = margin(l = -2, r = 0, t = 0, b = 0, unit = "pt"),
      axis.title = element_blank(),
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      plot.title = element_text(size = 6.0, face = "bold", margin = margin(b = 2)),
      plot.subtitle = element_blank()
    ) +
    labs(title = title)
  
  return(p)
}

# Generate Map Sub-panels (UOI using viridis, Predictions using inferno)
# Optimized dynamic ranges based on empirical raster percentiles to maximize contrast:
# GEDI UOI is bounded between 0.91 and 0.97.
# Predicted Biomass spans 0 to 4120, with 99% of pixels below 1400.
uoi_lims <- c(0.91, 0.97)
pred_lims <- c(0, 2000)

p_congo_uoi  <- make_map_panel(r_congo_cropped[["uoi"]], mcps_congo, "viridis", "C.1 Congo GEDI UOI (25 km)", "UOI", limits = uoi_lims, winsorize = TRUE)
p_congo_pred <- make_map_panel(r_pred_congo,             mcps_congo, "inferno", "C.2 Congo Predicted Biomass (25 km)", "Biomass", limits = pred_lims, winsorize = TRUE)
p_amazon_uoi  <- make_map_panel(r_amazon_cropped[["uoi"]], mcps_amazon, "viridis", "C.3 Amazon GEDI UOI (25 km)", "UOI", limits = uoi_lims, winsorize = TRUE)
p_amazon_pred <- make_map_panel(r_pred_amazon,             mcps_amazon, "inferno", "C.4 Amazon Predicted Biomass (25 km)", "Biomass", limits = pred_lims, winsorize = TRUE)

# Lay out Panel C as a 2x2 grid
fig_maps <- cowplot::plot_grid(
  p_congo_uoi, p_congo_pred,
  p_amazon_uoi, p_amazon_pred,
  ncol = 2,
  align = "hv",
  axis = "tblr"
)

# --- 8. Assemble and Save Master Figure --------------------------------------
cat("\nAssembling final 25km Multipanel Master Figure...\n")

# Row 1: A (Scatterplot) and B (Boxplots) side-by-side (giving B more width)
fig_top_row <- cowplot::plot_grid(
  p_scatter,
  p_box,
  ncol = 2,
  rel_widths = c(1.0, 1.45),
  align = "h",
  axis = "tb"
)

# Combine Row 1 (Scatter & Box) and Row 2 (2x2 Maps)
fig_master <- cowplot::plot_grid(
  fig_top_row,
  fig_maps,
  ncol = 1,
  rel_heights = c(1.0, 1.7)
)

# Save using the standard PNAS exporter
save_pnas(
  plot = fig_master,
  filename = "outputs/congo_ct_gee_25km_multipanel_synthesis.png",
  type = "double",
  height_cm = 19.5
)
cat("✓ Saved premium master figure to outputs/congo_ct_gee_25km_multipanel_synthesis.png\n")

# Copy to the active brain artifacts folder
brain_artifacts_dir <- "/home/j/.gemini/antigravity/brain/913e5cea-7c99-4b21-8124-ea8455da8457"
file.copy("outputs/congo_ct_gee_25km_multipanel_synthesis.png", 
          file.path(brain_artifacts_dir, "congo_ct_gee_25km_multipanel_synthesis.png"), 
          overwrite = TRUE)
cat("✓ Copied master figure to brain artifacts folder.\n")

cat("\n=== 25km Multipanel Synthesis Complete! ===\n")
